# Generated by Django 4.0.1 on 2022-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('posttitle', models.TextField(blank=True, db_column='PostTitle', null=True)),
                ('postcontent', models.TextField(blank=True, db_column='PostContent', null=True)),
                ('author', models.TextField(db_column='Author')),
                ('publishedon', models.DateTimeField(blank=True, db_column='PublishedOn', null=True)),
                ('updatedon', models.DateTimeField(blank=True, db_column='UpdatedOn', null=True)),
                ('deleted', models.BooleanField(db_column='Deleted')),
            ],
            options={
                'db_table': 'FIT_Blogpost',
            },
        ),
    ]
